name: Test Workflow

on: 
  workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test change
              run: echo "Hello World" > test.txt
            - name: commit changes
              run: |
                git config user.name "GitHub Actions"
                git config user.email "actions@github.com"
                git add test.txt
                git commit -m "Test change"
                git push